#CP-21 feat:  Logout from account
atlp-rwanda/phantom-be-codebandits pull request #11
Opened 2022-04-05 11:56 UTC by samuel-shyaka-dus

#### What does this PR do?
Gives an authenticated user the ability to logout, so that none else can access their account as well.

#### Description of the tasks to be completed
- [x] Authenticated user should be able to logout.
- [ ] Authenticated user should be able to access protected resourses/URLs.
- [ ] Appropriate error messages are displayed on unsuccessful attempts.

#### How should this be manually tested?
**Configure your environment based on the `.env.sample.md` then follow the following:**
```js
git checkout ft-sign-in-to-phantom-cp-8
git fetch
npm install
// if you don't have postgres installed, refer to the README for instructions
npm start
```
> **Testing the login route**
Use the below endpoints
```
POST   /api/v1/users    //Creating a user with {firstName, lastName, email & password}
POST   /api/v1/login    //Sign in with {email & password}
GET   /api/v1/logout    //Logout
```
#### Pre-requisites:

- Clone the project
- Make sure that Postgres is up and running

#### What are the relevant trello stories?
[#CP-21](https://trello.com/c/bhS4kERe/21-logout-from-account)

2022-04-07 20:44 UTC, feyton requested changes
@samuel-shyaka-dus 
This is great work. I left a review that needs special attention that affects the implementation. 
In the meantime that is great work.

2022-04-07 20:44 UTC, feyton commented on src/controllers/logout.controller.js
> +		await DataSource.query('TRUNCATE TABLE "RefreshToken"');
There is no need to drop the while table while deleting one refresh token. 
You have to check for just a specifically a token and remove that.

2022-04-07 21:20 UTC, feyton approved these changes, later dismissed

2022-04-07 21:23 UTC, feyton approved these changes, later dismissed

2022-04-07 21:23 UTC, Yvad60 approved these changes, later dismissed

2022-04-07 21:23 UTC, Abdulkeza submitted a review, later dismissed
Great job sam, I have seen that all the issues you had 3 hours ago were solved, now it is working as expected

2022-04-08 07:42 UTC, Yvad60 approved these changes

2022-04-09 16:00 UTC, feyton approved these changes
@samuel-shyaka-dus 
This is really a great work. The feature is well implemented. as we will integrate **Redis** into the project in the coming days. We will add a **token blacklist** so that users will be able to terminate their access_token before time which will be a great user experience. But as we are giving the token short life span. This is really great.

These changes can be merged.

2022-04-10 18:38 UTC, Jkadhuwa approved these changes

2022-04-10 18:39 UTC, merged